my/article/urls.py
from django.conf.urls import url
from article import views


urlpatterns = [
    url(r'^$', views.article, name='article'),
]

my/main/urls.py

from django.conf.urls import url
from main import views


urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^about/$', views.about ,name="about"),
    ]

my/my/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
 url(r'^admin/', admin.site.urls),
 url(r'^article/', include('article.urls', namespace='article')),
 url(r'^main/', include('main.urls', namespace='main')),
 url(r'^share/',include('share.urls', namespace='share')),
 url(r'^.*', include('main.urls')),
]

my/article/models.py
from django.db import models

my/main/models.py
from django.db import models

# Create your models here.

my/article/views.py
from django.shortcuts import render


def article(request):
    '''
    Render the article page
    '''
    return render(request, 'article/article.html')

my/main/views.py
from django.shortcuts import render
import datetime

def main(request):
    '''
    Render the main page
    '''
    context = {'like':'這裡是在MAIN.VIEW context like 顯示的字串', 'now':datetime.datetime.now()}
    return render(request, 'main/main.html', context)



def about(request):
    '''
    Render the about page
    '''
    return render(request, 'main/about.html')

my/article/templates/article/article.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>我的扭蛋</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
<link rel="stylesheet" href="{% static 'article/css/article.css' %}">
</head>
<body>
{% include 'main/menu.html' %}
<h2>這裡會介紹我自己的扭蛋</h2>
<img class=imgone src="{% static 'article/img/1.png' %}">
<img src="{% static 'article/img/2.png' %}">
<img src="{% static 'article/img/3.png' %}">
<img src="{% static 'article/img/4.png' %}">
</body>
</html>

my/main/templates/main/about.html
<!doctype html>
{% load staticfiles %}

<html>
<head>
<title>扭蛋種類</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">

</head>
<body>
{% include 'main/menu.html' %}

<h2>關於扭蛋</h2>
<p>這裡會介紹有甚麼扭蛋</p>


</body>
</html>

my/main/templates/main/main.html
<!doctype html>
{% load staticfiles %}

<html>
<head>
<title>我的扭蛋</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">

</head>
<body>
{% include 'main/menu.html' %}

<h2>哈囉</h2>
<p>{{ like }}</p>
<p>現在時間：{{ now }}</p>

</body>
</html>

my/main/templates/main/menu.html
<ul>
 <li><a href="{% url 'main:main' %}">首頁</a></li>
 <li><a href="{% url 'main:about' %}">關於扭蛋</a></li>
 <li><a href="{% url 'article:article' %}">我的扭蛋</a></li>
 <li><a href="{% url 'share:share' %}">分享扭蛋</a></li>
 
</ul>